import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalState from '@/context'
import '../assets/boxicons-2.1.2/css/boxicons.min.css'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalState>

          <body className={inter.className}>{children}</body>
       
      </GlobalState>
      </html>
  )
}
